--DECLARARCION DE VARIABLES
  DECLARE IDS_ARRAY ARRAY<INT64>;
  DECLARE IDS_SHP_INT ARRAY<INT64>;
  DECLARE IDS_SHP_NUM ARRAY<NUMERIC>;
  DECLARE IDS_SHP_STR ARRAY<STRING>;

--SETEO DE VARIABLES  ################################################################################

SET IDS_ARRAY = (
  SELECT
  ARRAY_AGG(CAST(DATS AS INT64)) AS ID
  FROM UNNEST (SPLIT(@ARRAY_GS,',')) AS DATS
);

  SET IDS_SHP_INT = IDS_ARRAY;

  SET IDS_SHP_STR = ( -- LISTA CONVERSION DE SHP A STRING
    SELECT ARRAY_AGG(CAST(STR AS STRING))
    FROM UNNEST(IDS_ARRAY) AS STR
  );

  SET IDS_SHP_NUM = ( -- LISTA CONVERSION DE SHP A NUMERIC
    SELECT ARRAY_AGG(CAST(NUM AS NUMERIC))
    FROM UNNEST(IDS_ARRAY) AS NUM
  );


--TABLAS DE SUBCONSULTAS
  WITH
    #SUBTABLA ARRAY
    IDS_ARRAY_TAB AS (
      SELECT 
        SHP AS SHP_ID
      FROM UNNEST(IDS_SHP_INT) AS SHP
    ),

    #SUBTABLA DETALLES DEL SHIPMENTS__________________________________________________________________
    TAB_DET AS (
      SELECT
        SHP_SHIPMENT_ID AS SHP_ID,
        STRING_AGG(ITEM.SHP_ITEM_DESC, '\n') AS DESCRIPTION,
        SHP_ORDER_COST AS PRICE_MXN,
        SHP_RECEIVER_CITY_NAME AS CITY
      FROM WHOWNER.BT_SHP_SHIPMENTS, UNNEST(ITEMS) AS ITEM
      WHERE SHP_SHIPMENT_ID IN UNNEST(IDS_SHP_INT)
      GROUP BY SHP_SHIPMENT_ID, SHP_ORDER_COST, SHP_RECEIVER_CITY_NAME
    ),

    #SUBTABLA ÚLTIMO ESTATUS___________________________________________________________________________
    TAB_STS AS (
      SELECT
        SHP_SHIPMENT_ID AS SHP_ID,
        SHP_LG_STATUS AS LAST_LOCATE,
        SHP_LG_SUB_STATUS AS SHP_STATUS,
        CAST(SHP_LG_PROMISE_DT_FROM AS DATE) AS DATE_PROMISE
      FROM WHOWNER.BT_SHP_LG_SHIPMENTS
      WHERE SHP_SHIPMENT_ID IN UNNEST(IDS_SHP_INT)
    ),

    #SUBTABLA ÚLTIMO RUTEO_____________________________________________________________________________
    TAB_RTS AS (
      SELECT
        A1 AS SHP_ID,
        A3 AS LD_ROUTE,
        A2 AS ID_ROUTE,
        C1 AS LAST_COMPANY
      FROM (
          SELECT
            ROW_NUMBER()
            OVER(PARTITION BY A.SHP_SHIPMENT_ID ORDER BY CAST(A.SHP_LG_ROUTE_INIT_DATE AS DATE) DESC) AS FN,
            A.SHP_SHIPMENT_ID AS A1,
            A.SHP_LG_ROUTE_ID AS A2,
            CAST(A.SHP_LG_ROUTE_INIT_DATE AS DATE) AS A3,     
            C.SHP_COMPANY_NAME AS C1,
          FROM WHOWNER.BT_SHP_LG_SHIPMENTS_ROUTES AS A
          LEFT JOIN WHOWNER.LK_SHP_COMPANIES AS C ON (C.SHP_COMPANY_ID = A.SHP_COMPANY_ID)
          WHERE A.SHP_SHIPMENT_ID IN UNNEST(IDS_SHP_INT)
          ORDER BY A.SHP_SHIPMENT_ID
      )
      WHERE FN = 1
    ),

    #SUBTABLA ÚLTIMO CONTENEDOR________________________________________________________________________
    TAB_CTN AS (
      SELECT
        A1 AS SHP_ID,
        A2 AS CONTAINER
      FROM (
          SELECT 
            ROW_NUMBER()
            OVER(PARTITION BY IDS ORDER BY CONTAINER_DATE_SORTING DESC) AS FN,
            IDS AS A1,
            CONTAINER.CLUSTER_ID AS A2
          FROM WHOWNER.BT_SHP_MT_LOGISTIC_CONTAINER,
          UNNEST(CONTAINER.SHIPMENT.SHIPMENT_IDS) AS IDS
          WHERE IDS IN UNNEST(IDS_SHP_INT)
      )
      WHERE FN = 1
    )

--CONSULTA UNIFICADA  #################################################################################
  SELECT
    C.DESCRIPTION,
    C.PRICE_MXN,
  
    E.LAST_LOCATE,
    E.SHP_STATUS,     
    E.DATE_PROMISE,

    C.CITY,
    F.LD_ROUTE,
    F.ID_ROUTE,
    F.LAST_COMPANY,    
    G.CONTAINER

  FROM IDS_ARRAY_TAB AS A
  LEFT JOIN TAB_DET AS C ON (C.SHP_ID = A.SHP_ID)
  LEFT JOIN TAB_STS AS E ON (E.SHP_ID = A.SHP_ID)
  LEFT JOIN TAB_RTS AS F ON (F.SHP_ID = A.SHP_ID)
  LEFT JOIN TAB_CTN AS G ON (G.SHP_ID = A.SHP_ID)
  
  LIMIT 1000