--DECLARARCION DE VARIABLES
  DECLARE INV_LIST_ARRAY ARRAY<INT64>;
  DECLARE S_INT ARRAY<INT64>;
  DECLARE S_NUM ARRAY<NUMERIC>;
  DECLARE S_STR ARRAY<STRING>;

  SET INV_LIST_ARRAY = (
    ARRAY(
      SELECT CAST(num AS INT64)
      FROM UNNEST(SPLIT(@ARRAY_GS,',')) AS num
    )
  );


--AJUSTE DE ARRAY DE IDS
  SET S_INT = INV_LIST_ARRAY;
  SET S_NUM = (
    SELECT ARRAY_AGG(CAST(num AS NUMERIC))
    FROM UNNEST(S_INT) AS num
  );

--TABLAS DE SUBCONSULTAS
  WITH
    #SUBTABLA ARRAY
    INV_LIST_TABLE AS (
      SELECT 
        SHP_ID_INV AS SHP_ID
      FROM UNNEST(INV_LIST_ARRAY) AS SHP_ID_INV
    ),
    #SUBTABLA DESCRIPCION
    T_DESC AS (
      SELECT
      SHP_SHIPMENT_ID AS SHP_ID,
      STRING_AGG(ITEM.SHP_ITEM_DESC, '\n') AS DESCRIPTION,
      SHP_ORDER_COST AS COST_MXN,
      SHP_ORDER_COST_USD AS COST_USD
      FROM WHOWNER.BT_SHP_SHIPMENTS,
      UNNEST(ITEMS) AS ITEM
      WHERE SHP_SHIPMENT_ID IN UNNEST(S_INT)
      GROUP BY SHP_SHIPMENT_ID,SHP_ORDER_COST,SHP_ORDER_COST_USD
    ),

    #SUBTABLA RECEPCION
    T_FS AS (
      SELECT
      CAST(SHP_SHIPMENT_ID AS INT64) AS SHP_ID,
      MIN (CAST(DATETIME_SUB(SHP_LG_SHIPMENT_CHK_DT, INTERVAL 2 HOUR) AS TIME)) AS TIME_SORTING
      FROM WHOWNER.BT_SHP_LG_SHIPMENT_CHECKPOINTS
      WHERE SHP_SHIPMENT_ID IN UNNEST(S_NUM)
      AND SHP_LG_SUB_STATUS = 'sorting'
      GROUP BY SHP_SHIPMENT_ID
    ),

    #SUBTABLA ESTATUS-1
    TAB_PRE1 AS (
      SELECT
      ID,
      PRE_LOCATION,
      PRE_STATUS,
      DATE_PRE
      FROM (
        SELECT
        ROW_NUMBER() OVER(PARTITION BY SHP_SHIPMENT_ID ORDER BY SHP_LG_SHIPMENT_CHK_DT DESC) AS ROW_NUM,
        SHP_SHIPMENT_ID AS ID,
        SHP_LG_STATUS AS PRE_LOCATION,
        SHP_LG_SUB_STATUS AS PRE_STATUS,
        CAST(DATETIME_SUB(SHP_LG_SHIPMENT_CHK_DT, INTERVAL 2 HOUR) as date) as DATE_PRE,
        FROM WHOWNER.BT_SHP_LG_SHIPMENT_CHECKPOINTS
        WHERE SHP_SHIPMENT_ID IN UNNEST(S_NUM)
      )
      WHERE ROW_NUM = 1
    ),

    #SUBTABLA ESTATUS-2
    TAB_PRE2 AS (
      SELECT
      ID,
      PRE_LOCATION,
      PRE_STATUS,
      DATE_PRE
      FROM (
        SELECT
        ROW_NUMBER() OVER(PARTITION BY SHP_SHIPMENT_ID ORDER BY SHP_LG_SHIPMENT_CHK_DT DESC) AS ROW_NUM,
        SHP_SHIPMENT_ID AS ID,
        SHP_LG_STATUS AS PRE_LOCATION,
        SHP_LG_SUB_STATUS AS PRE_STATUS,
        CAST(DATETIME_SUB(SHP_LG_SHIPMENT_CHK_DT, INTERVAL 2 HOUR) as date) as DATE_PRE,
        FROM WHOWNER.BT_SHP_LG_SHIPMENT_CHECKPOINTS
        WHERE SHP_SHIPMENT_ID IN UNNEST(S_NUM)
      )
      WHERE ROW_NUM = 2
    ),

    #SUBTABLA ESTATUS-3
    TAB_PRE3 AS (
      SELECT
      ID,
      PRE_LOCATION,
      PRE_STATUS,
      DATE_PRE
      FROM (
        SELECT
        ROW_NUMBER() OVER(PARTITION BY SHP_SHIPMENT_ID ORDER BY SHP_LG_SHIPMENT_CHK_DT DESC) AS ROW_NUM,
        SHP_SHIPMENT_ID AS ID,
        SHP_LG_STATUS AS PRE_LOCATION,
        SHP_LG_SUB_STATUS AS PRE_STATUS,
        CAST(DATETIME_SUB(SHP_LG_SHIPMENT_CHK_DT, INTERVAL 2 HOUR) as date) as DATE_PRE,
        FROM WHOWNER.BT_SHP_LG_SHIPMENT_CHECKPOINTS
        WHERE SHP_SHIPMENT_ID IN UNNEST(S_NUM)
      )
      WHERE ROW_NUM = 3
    )


--EJECUCION DE QUERY
  SELECT
    #ILT.SHP_ID,
    TDESC.DESCRIPTION,
    TDESC.COST_MXN,
    TDESC.COST_USD,
    REC.TIME_SORTING,

    P1.PRE_LOCATION AS LOCATION_0,
    P1.PRE_STATUS AS STATUS_0,
    P1.DATE_PRE AS DATE_0,

    P2.PRE_LOCATION AS LOCATION_1,
    P2.PRE_STATUS AS STATUS_1,
    P2.DATE_PRE AS DATE_1,

    P3.PRE_LOCATION AS LOCATION_2,
    P3.PRE_STATUS AS STATUS_2,
    P3.DATE_PRE AS DATE_2

  FROM INV_LIST_TABLE AS ILT
    LEFT JOIN T_DESC AS TDESC ON (TDESC.SHP_ID = ILT.SHP_ID)
    LEFT JOIN T_FS AS REC ON (REC.SHP_ID = ILT.SHP_ID)
    LEFT JOIN TAB_PRE1 AS P1  ON (P1.ID = ILT.SHP_ID)
    LEFT JOIN TAB_PRE2 AS P2  ON (P2.ID = ILT.SHP_ID)
    LEFT JOIN TAB_PRE3 AS P3  ON (P3.ID = ILT.SHP_ID)

  LIMIT 10000